%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/melodic/.*$
%global __requires_exclude_from ^/opt/ros/melodic/.*$

Name:           ros-melodic-cob-gazebo-worlds
Version:        0.7.3
Release:        1%{?dist}
Summary:        ROS cob_gazebo_worlds package

License:        Apache 2.0
URL:            http://ros.org/wiki/cob_gazebo_worlds
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-cob-default-env-config
Requires:       ros-melodic-controller-manager
Requires:       ros-melodic-gazebo-msgs
Requires:       ros-melodic-gazebo-ros
Requires:       ros-melodic-gazebo-ros-control
Requires:       ros-melodic-joint-state-controller
Requires:       ros-melodic-joint-state-publisher
Requires:       ros-melodic-position-controllers
Requires:       ros-melodic-robot-state-publisher
Requires:       ros-melodic-roslaunch
Requires:       ros-melodic-rospy
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-tf
Requires:       ros-melodic-velocity-controllers
Requires:       ros-melodic-xacro
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-cob-default-env-config
BuildRequires:  ros-melodic-roslaunch
BuildRequires:  ros-melodic-rostest

%description
This package provides some worlds for gazebo simulation.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/melodic

%changelog
* Sat Nov 09 2019 Jannik Abbenseth <jba@ipa.fhg.de> - 0.7.3-1
- Autogenerated by Bloom

