<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
	name="automotive-assembly-line">

  <!-- properties -->
  <xacro:property name="base_width" value="0.1" />
  <xacro:property name="base_length" value="250" />
  <xacro:property name="base_height" value="0.1" />
  <xacro:property name="base_mass" value="5.0" />

  <xacro:property name="belt_width" value="4" />
  <xacro:property name="belt_length" value="250" />
  <xacro:property name="belt_height" value="0.1" />
  <xacro:property name="belt_mass" value="5.0" />

  <xacro:property name="box_width" value="2.0" />
  <xacro:property name="box_length" value="3.8" />
  <xacro:property name="box_height" value="0.4" />
  <xacro:property name="box_mass" value="0.1" />

  <xacro:property name="boxes_distance" value="10"/>
  <xacro:property name="world_to_base_offset_x" value="5" />

  <!-- macros -->
  <xacro:macro name="box_inertial" params="x y z mass *origin">
    <inertial>
      <mass value="${mass}" />
      <xacro:insert_block name="origin" />
      <inertia ixx="${0.0833333 * mass * (y*y + z*z)}" ixy="0.0" ixz="0.0"
          iyy="${0.0833333 * mass * (x*x + z*z)}" iyz="0.0"
          izz="${0.0833333 * mass * (x*x + y*y)}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="new_box" params="new_box_num">
    <link name="box_${new_box_num}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
	  <box size="${box_width} ${box_length} ${box_height}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
  	  <box size="${box_width} ${box_length} ${box_height}"/>
        </geometry>
      </collision>
      <xacro:default_inertial/>
    </link>
    <gazebo reference="box_${new_box_num}">
      <material>Gazebo/Grey</material>
    </gazebo>
    <joint name="belt_to_box_${new_box_num}" type="fixed">
       <origin xyz="0 ${new_box_num*(box_length+boxes_distance)-belt_length/2} ${box_height/2}"/>
       <parent link="my_belt"/>
       <child link="box_${new_box_num}"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="new_object" params="new_object_num *mesh *origin">
    <link name="world_object_${new_object_num}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <xacro:insert_block name = "mesh"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <xacro:insert_block name = "mesh"/>
        </geometry>
      </collision>
      <xacro:default_inertial/>
    </link>
    <gazebo reference="world_object_${new_object_num}">
      <static>true</static>
    </gazebo>
    <joint name="bin_joint_${new_object_num}" type="fixed">
       <xacro:insert_block name="origin"/>
       <parent link="belt_base_link"/>
       <child link="world_object_${new_object_num}"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="default_inertial">
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>
  </xacro:macro>

  <!-- gazebo plugin -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>world</robotNamespace>
      <robotParam>/world_description</robotParam>
    </plugin>
  </gazebo>

  <!-- world link -->
  <link name="world" />

  <!-- base link -->
  <link name="belt_base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${base_width} ${base_length} ${base_height}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${base_width} ${base_length} ${base_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertial x="${base_width}" y="${base_length}" z="${base_height}" mass="${base_mass}">
	<origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:box_inertial>
  </link>
  <gazebo reference="belt_base_link">
	<material>Gazebo/Black</material>
  </gazebo>
  <joint name="world_joint" type="fixed">
     <parent link="world"/>
     <child link="belt_base_link"/>
     <origin xyz = "${world_to_base_offset_x} 0 ${base_height/2}"/>
  </joint>

  <!-- moving belt -->
  <link name="my_belt">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${belt_width} ${belt_length} ${belt_height}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${belt_width} ${belt_length} ${belt_height}" />
      </geometry>
    </collision>
    <xacro:box_inertial x="${belt_width}" y="${belt_length}" z="${belt_height}" mass="${belt_mass}">
	<origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:box_inertial>
  </link>
  <gazebo reference="my_belt">
    <material>Gazebo/WoodFloor</material>
  </gazebo>
  <joint name="base_to_belt" type="prismatic">
    <parent link="belt_base_link"/>
    <child link="my_belt"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/> 
    <origin xyz="${belt_width/2+0.5} 0 ${base_height/2}"/>
    <limit lower="-100000" upper="100000" velocity="0.5" effort="10"/>
  </joint>

  <!--boxes-->
  <xacro:new_box new_box_num="1"/>
  <xacro:new_box new_box_num="2"/>
  <xacro:new_box new_box_num="3"/>
  <xacro:new_box new_box_num="4"/>
  <xacro:new_box new_box_num="5"/>
  <xacro:new_box new_box_num="6"/>
  <xacro:new_box new_box_num="7"/>
  <xacro:new_box new_box_num="8"/>
  <xacro:new_box new_box_num="9"/>
  <xacro:new_box new_box_num="10"/>
  <xacro:new_box new_box_num="11"/>
  <xacro:new_box new_box_num="12"/>
  <xacro:new_box new_box_num="13"/>
  <xacro:new_box new_box_num="14"/>
  <xacro:new_box new_box_num="15"/>
  <xacro:new_box new_box_num="16"/>
  <xacro:new_box new_box_num="17"/>

  <!--world objects-->
  <xacro:new_object new_object_num="1" >
    <mesh filename="package://cob_gazebo_worlds/Media/models/dump-bin-retail/model.dae"/>
    <origin xyz="-7 -15 0" />
  </xacro:new_object>
  <xacro:new_object new_object_num="2" >
    <mesh filename="package://cob_gazebo_worlds/Media/models/dump-bin-retail/model.dae"/>
    <origin xyz="-7 -10 0" />
  </xacro:new_object>
  <xacro:new_object new_object_num="3" >
    <mesh filename="package://cob_gazebo_worlds/Media/models/dump-bin-retail/model.dae"/>
    <origin xyz="-7 -5 0" />
  </xacro:new_object>
  <xacro:new_object new_object_num="4" >
    <mesh filename="package://cob_gazebo_worlds/Media/models/dump-bin-retail/model.dae"/>
    <origin xyz="-7 0 0" />
  </xacro:new_object>
  <xacro:new_object new_object_num="5" >
    <mesh filename="package://cob_gazebo_worlds/Media/models/dump-bin-retail/model.dae"/>
    <origin xyz="-7 5 0" />
  </xacro:new_object>
  <xacro:new_object new_object_num="6" >
    <mesh filename="package://cob_gazebo_worlds/Media/models/dump-bin-retail/model.dae"/>
    <origin xyz="5 -15 0" />
  </xacro:new_object>
  <xacro:new_object new_object_num="7" >
    <mesh filename="package://cob_gazebo_worlds/Media/models/dump-bin-retail/model.dae"/>
    <origin xyz="5 -10 0" />
  </xacro:new_object>
  <xacro:new_object new_object_num="8" >
    <mesh filename="package://cob_gazebo_worlds/Media/models/dump-bin-retail/model.dae"/>
    <origin xyz="5 -5 0" />
  </xacro:new_object>
  <xacro:new_object new_object_num="9" >
    <mesh filename="package://cob_gazebo_worlds/Media/models/dump-bin-retail/model.dae"/>
    <origin xyz="5 0 0" />
  </xacro:new_object>
  <xacro:new_object new_object_num="10" >
    <mesh filename="package://cob_gazebo_worlds/Media/models/dump-bin-retail/model.dae"/>
    <origin xyz="5 5 0" />
  </xacro:new_object>
  <xacro:new_object new_object_num="11" >
    <mesh filename="package://cob_gazebo_objects/Media/models/cabinet_ikea_galant.dae"/>
    <origin xyz="-9 0 0" />
  </xacro:new_object>

  <transmission name="belt_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="base_to_belt">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="belt_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
